### ISSUE TITLE
 : )

### ISSUE THREAD

**Issue by LesterWeng** [zhoutk/gels#2]
您好 最近刚开始研究node koa2 graphQl，看到您的项目，现在还不大能看得懂，打算好好学习下，请问有什么推荐的学习路线嘛 : )

**Comment by zhoutk** [comment]
英文阅读无障碍的话，最好直接看官方文档。我使用的是apollo sever 2.0改变还是很大的，中文资料也少，直接自己慢慢看官方文档。

**Comment by LesterWeng** [comment]
> 英文阅读无障碍的话，最好直接看官方文档。我使用的是apollo sever 2.0改变还是很大的，中文资料也少，直接自己慢慢看官方文档。

好的，感谢
